// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.1
//   protoc               v3.12.4
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface Token {
  token: string;
}

export interface UserDto {
  email: string;
  password: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface LoginServiceClient {
  login(request: UserDto): Observable<Token>;
}

export interface LoginServiceController {
  login(request: UserDto): Promise<Token> | Observable<Token> | Token;
}

export function LoginServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("LoginService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("LoginService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LOGIN_SERVICE_NAME = "LoginService";
